name: Main on push

on:
  push:
    branches: [ master ]

  workflow_dispatch:
    inputs:
      release_notes:
        type: string
        required: true
        default: 'Manual Debug Build'
        description: 'Release Notes'

jobs:
  build:
    name: Building and distributing app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17.0'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Create google-services.json
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > app/google-services.json

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Execute Gradle command - assembleDebug
        run: ./gradlew assembleDebug --stacktrace

      - name: Create service credentials file
        run: echo '${{ secrets.CREDENTIAL_FILE_CONTENT_2 }}' > service-credentials.json

      - name: Upload Artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFile: service-credentials.json
          groups: testers
          file: app/build/outputs/apk/debug/app-debug.apk
          releaseNotes: ${{ inputs.release_notes || format('Build from commit {0}', github.sha) }}